name: Hugo Actions # 名字自取

on:
  push:
    branches:
      - main  # 这里的意思是当 main 分支发生 push 的时候，运行下面的 jobs

jobs:
  deploy: 
    runs-on: ubuntu-latest 	# 在什么环境运行任务
    steps:
      - uses: actions/checkout@v4   # 引用 actions/checkout 这个 action，与所在的 github 仓库同名
        with:
         submodules: true  # Fetch Hugo themes (true OR recursive) 获取 submodule 主题
         fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
         
      - name: Setup Hugo	# 步骤名自取
        uses: peaceiris/actions-hugo@v2   # Hugo 官方提供的 action，用于在任务环境中获取 hugo
        with:
          hugo-version: '0.122.0'	# 获取指定版本的 hugo
          extended: false

      - name: Build Site
        run: |
          pwd
          ls
          cp -R exampleSite/* .
          hugo --themesDir ../ --baseURL https://yukiryo.github.io/WebStack-Hugo/
          
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3	  # 一个自动发布 github pages 的 action
        with:
          # external_repository: shenweiyan/WebStack-Hugo  # 默认发布到当前 repo
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自动提供的 Token
          # cname: webstack-hugo.weiyan.cc # 移除 CNAME，除非你有自定义域名
          full_commit_message: ${{ github.event.head_commit.message }}
